In [15]:
pip install pandas

Requirement already satisfied: pandas in ./HyperDB/lib/python3.12/site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in ./HyperDB/lib/python3.12/site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./HyperDB/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./HyperDB/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./HyperDB/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in ./HyperDB/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
pip install openpyxl

Requirement already satisfied: openpyxl in ./HyperDB/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in ./HyperDB/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [59]:
import os
import pandas as pd

In [60]:
df = pd.DataFrame(pd.read_excel("ASIAN_CA_PO_Suggest_DEV.xlsx"))
df = df.dropna(subset=['Item'])
print(df.columns)
for col in df.columns:
    print(f"Updated Column: {col}")

Index([           'Item',     'Description', 'Report Category',
        '미취급\nTOSS\n지자체',        'B1\n4wks',        'B1\n13Wk',
               'S\n4wks',        'S\n13wks',        'TR\n4wks',
             'TR\n13wks',
       ...
             '210680312',       '210680292',       '210680316',
             '210680315',       '210680314',       '210680303',
             '210680307',       '210680306',       '210680308',
             '210273840'],
      dtype='object', length=250)
Updated Column: Item
Updated Column: Description
Updated Column: Report Category
Updated Column: 미취급
TOSS
지자체
Updated Column: B1
4wks
Updated Column: B1
13Wk
Updated Column: S
4wks
Updated Column: S
13wks
Updated Column: TR
4wks
Updated Column: TR
13wks
Updated Column: B1
Updated Column: 7
Updated Column: 8
Updated Column: 9
Updated Column: 10
Updated Column: 11
Updated Column: 12
Updated Column: 1
Updated Column: 2
Updated Column: 3
Updated Column: 4
Updated Column: 5
Updated Column: 6
Updated Column: S
Updated Column: 7.1
Updated Column: 8.1
Updated Column: 9.1
Updated Column: 10.1
Updated Column: 11.1
Updated Column: 12.1
Updated Column: 1.1
Updated Column: 2.1
Updated Column: 3.1
Updated Column: 4.1
Updated Column: 5.1
Updated Column: 6.1
Updated Column: Buyer's
Decision
Updated Column: Stock
Qty
Updated Column: Case/Pallet
Updated Column: Stock Pallet Qty
Updated Column: On-order
Qty
Updated Column: Cur
 Turn Over
Updated Column: 현재고
 Turn Over
Updated Column: Suggested
Order Qty
Updated Column: Actual Order
GSC Qty
Updated Column: Buyer
Opinion
Updated Column: 도착시 Turn Over(week)
Updated Column: Lead Time
(Week)
Updated Column: 최소재고
(Week)
Updated Column: 발주단위
(Week)
Updated Column: Max재고
(Week)
Updated Column: ReOrder Point
(Week)
Updated Column: buyer
Updated Column: categoryL1
Updated Column: UPC
Updated Column: Free
Updated Column: On Order
Updated Column: CW
Updated Column: C+1W
Updated Column: C+2W
Updated Column: C+3W
Updated Column: C+4W
Updated Column: C+5W
Updated Column: C+6W
Updated Column: C+7W
Updated Column: C+8W
Updated Column: C+9W
Updated Column: C+10W
Updated Column: C+11W
Updated Column: C+12W
Updated Column: C+13W
Updated Column: C+14W
Updated Column: C+15W
Updated Column: C+16W
Updated Column: C+17W
Updated Column: C+18W
Updated Column: C+19W
Updated Column: C+20W
Updated Column: C+21W
Updated Column: C+22W
Updated Column: After 22W
Updated Column: INV
FCST
Updated Column: CW.1
Updated Column: C+1W.1
Updated Column: C+2W.1
Updated Column: C+3W.1
Updated Column: C+4W.1
Updated Column: C+5W.1
Updated Column: C+6W.1
Updated Column: C+7W.1
Updated Column: C+8W.1
Updated Column: C+9W.1
Updated Column: C+10W.1
Updated Column: C+11W.1
Updated Column: C+12W.1
Updated Column: C+13W.1
Updated Column: C+14W.1
Updated Column: C+15W.1
Updated Column: C+16W.1
Updated Column: C+17W.1
Updated Column: C+18W.1
Updated Column: C+19W.1
Updated Column: C+20W.1
Updated Column: C+21W.1
Updated Column: C+22W.1
Updated Column: PO
Updated Column: 210678826
Updated Column: 210275906
Updated Column: 210672824
Updated Column: 210680517
Updated Column: 210679779
Updated Column: 210673606
Updated Column: 210671918
Updated Column: 210677169
Updated Column: 210677166
Updated Column: 210677462
Updated Column: 210677163
Updated Column: 210677170
Updated Column: 210275700
Updated Column: 210678101
Updated Column: 210680492
Updated Column: 210680922
Updated Column: 210680923
Updated Column: 210672823
Updated Column: 210678828
Updated Column: 210676604
Updated Column: 210677881
Updated Column: 210677878
Updated Column: 210676603
Updated Column: 210672814
Updated Column: 210672355
Updated Column: 210672072
Updated Column: 210672352
Updated Column: 210677446
Updated Column: 210275701
Updated Column: 210672509
Updated Column: 210680493
Updated Column: 210275702
Updated Column: 210678486
Updated Column: 210674066
Updated Column: 210679537
Updated Column: 210674825
Updated Column: 210679360
Updated Column: 210678829
Updated Column: 210677746
Updated Column: 210678137
Updated Column: 210678139
Updated Column: 210676977
Updated Column: 210676976
Updated Column: 210678134
Updated Column: 210678135
Updated Column: 210670485
Updated Column: 210678107
Updated Column: 210670490
Updated Column: 210672819
Updated Column: 210677153
Updated Column: 210679671
Updated Column: 210676607
Updated Column: 210678509
Updated Column: 210679361
Updated Column: 210679538
Updated Column: 210677182
Updated Column: 210680004
Updated Column: 210679177
Updated Column: 210678115
Updated Column: 210677691
Updated Column: 210677454
Updated Column: 210677675
Updated Column: 210677703
Updated Column: 210678385
Updated Column: 210677088
Updated Column: 210680821
Updated Column: 210673106
Updated Column: 210673088
Updated Column: 210673101
Updated Column: 210673096
Updated Column: 210673099
Updated Column: 210673104
Updated Column: 210673107
Updated Column: 210673089
Updated Column: 210673103
Updated Column: 210673105
Updated Column: 210677702
Updated Column: 210680320
Updated Column: 210680323
Updated Column: 210680335
Updated Column: 210680336
Updated Column: 210266277
Updated Column: 210680516
Updated Column: 210680513
Updated Column: 210679720
Updated Column: 210680338
Updated Column: 210677448
Updated Column: 210680337
Updated Column: 210680340
Updated Column: 210680322
Updated Column: 210266274
Updated Column: 210680707
Updated Column: 210679539
Updated Column: 210677912
Updated Column: 210679540
Updated Column: 210678116
Updated Column: 210677455
Updated Column: 210674861
Updated Column: 210679724
Updated Column: 210677452
Updated Column: 210675948
Updated Column: 210675852
Updated Column: 210675846
Updated Column: 210675853
Updated Column: 210675856
Updated Column: 210675857
Updated Column: 210675851
Updated Column: 210675947
Updated Column: 210675850
Updated Column: 210675949
Updated Column: 210675858
Updated Column: 210675845
Updated Column: 210675860
Updated Column: 210675855
Updated Column: 210675854
Updated Column: 210677458
Updated Column: 210268493
Updated Column: 210268490
Updated Column: 210268495
Updated Column: 210268496
Updated Column: 210268494
Updated Column: 210268497
Updated Column: 210678158
Updated Column: 210679756
Updated Column: 210679754
Updated Column: 210679753
Updated Column: 210679757
Updated Column: 210679749
Updated Column: 210680296
Updated Column: 210680318
Updated Column: 210680300
Updated Column: 210680319
Updated Column: 210680317
Updated Column: 210680294
Updated Column: 210680312
Updated Column: 210680292
Updated Column: 210680316
Updated Column: 210680315
Updated Column: 210680314
Updated Column: 210680303
Updated Column: 210680307
Updated Column: 210680306
Updated Column: 210680308
Updated Column: 210273840

In [61]:
df.columns = df.columns.str.replace('\n', ' ', regex=False)
print(df.columns)

Index([           'Item',     'Description', 'Report Category',
          '미취급 TOSS 지자체',         'B1 4wks',         'B1 13Wk',
                'S 4wks',         'S 13wks',         'TR 4wks',
              'TR 13wks',
       ...
             '210680312',       '210680292',       '210680316',
             '210680315',       '210680314',       '210680303',
             '210680307',       '210680306',       '210680308',
             '210273840'],
      dtype='object', length=250)

In [62]:
for col in df.columns:
    print(f"Updated Column: {col}")

Updated Column: Item
Updated Column: Description
Updated Column: Report Category
Updated Column: 미취급 TOSS 지자체
Updated Column: B1 4wks
Updated Column: B1 13Wk
Updated Column: S 4wks
Updated Column: S 13wks
Updated Column: TR 4wks
Updated Column: TR 13wks
Updated Column: B1
Updated Column: nan
Updated Column: nan
Updated Column: nan
Updated Column: nan
Updated Column: nan
Updated Column: nan
Updated Column: nan
Updated Column: nan
Updated Column: nan
Updated Column: nan
Updated Column: nan
Updated Column: nan
Updated Column: S
Updated Column: 7.1
Updated Column: 8.1
Updated Column: 9.1
Updated Column: 10.1
Updated Column: 11.1
Updated Column: 12.1
Updated Column: 1.1
Updated Column: 2.1
Updated Column: 3.1
Updated Column: 4.1
Updated Column: 5.1
Updated Column: 6.1
Updated Column: Buyer's  Decision
Updated Column: Stock  Qty
Updated Column: Case/Pallet
Updated Column: Stock Pallet Qty
Updated Column: On-order  Qty
Updated Column: Cur   Turn Over
Updated Column: 현재고   Turn Over
Updated Column: Suggested  Order Qty
Updated Column: Actual Order  GSC Qty
Updated Column: Buyer  Opinion
Updated Column: 도착시 Turn Over(week)
Updated Column: Lead Time  (Week)
Updated Column: 최소재고 (Week)
Updated Column: 발주단위 (Week)
Updated Column: Max재고 (Week)
Updated Column: ReOrder Point  (Week)
Updated Column: buyer
Updated Column: categoryL1
Updated Column: UPC
Updated Column: Free
Updated Column: On Order
Updated Column: CW
Updated Column: C+1W
Updated Column: C+2W
Updated Column: C+3W
Updated Column: C+4W
Updated Column: C+5W
Updated Column: C+6W
Updated Column: C+7W
Updated Column: C+8W
Updated Column: C+9W
Updated Column: C+10W
Updated Column: C+11W
Updated Column: C+12W
Updated Column: C+13W
Updated Column: C+14W
Updated Column: C+15W
Updated Column: C+16W
Updated Column: C+17W
Updated Column: C+18W
Updated Column: C+19W
Updated Column: C+20W
Updated Column: C+21W
Updated Column: C+22W
Updated Column: After 22W
Updated Column: INV FCST
Updated Column: CW.1
Updated Column: C+1W.1
Updated Column: C+2W.1
Updated Column: C+3W.1
Updated Column: C+4W.1
Updated Column: C+5W.1
Updated Column: C+6W.1
Updated Column: C+7W.1
Updated Column: C+8W.1
Updated Column: C+9W.1
Updated Column: C+10W.1
Updated Column: C+11W.1
Updated Column: C+12W.1
Updated Column: C+13W.1
Updated Column: C+14W.1
Updated Column: C+15W.1
Updated Column: C+16W.1
Updated Column: C+17W.1
Updated Column: C+18W.1
Updated Column: C+19W.1
Updated Column: C+20W.1
Updated Column: C+21W.1
Updated Column: C+22W.1
Updated Column: PO
Updated Column: 210678826
Updated Column: 210275906
Updated Column: 210672824
Updated Column: 210680517
Updated Column: 210679779
Updated Column: 210673606
Updated Column: 210671918
Updated Column: 210677169
Updated Column: 210677166
Updated Column: 210677462
Updated Column: 210677163
Updated Column: 210677170
Updated Column: 210275700
Updated Column: 210678101
Updated Column: 210680492
Updated Column: 210680922
Updated Column: 210680923
Updated Column: 210672823
Updated Column: 210678828
Updated Column: 210676604
Updated Column: 210677881
Updated Column: 210677878
Updated Column: 210676603
Updated Column: 210672814
Updated Column: 210672355
Updated Column: 210672072
Updated Column: 210672352
Updated Column: 210677446
Updated Column: 210275701
Updated Column: 210672509
Updated Column: 210680493
Updated Column: 210275702
Updated Column: 210678486
Updated Column: 210674066
Updated Column: 210679537
Updated Column: 210674825
Updated Column: 210679360
Updated Column: 210678829
Updated Column: 210677746
Updated Column: 210678137
Updated Column: 210678139
Updated Column: 210676977
Updated Column: 210676976
Updated Column: 210678134
Updated Column: 210678135
Updated Column: 210670485
Updated Column: 210678107
Updated Column: 210670490
Updated Column: 210672819
Updated Column: 210677153
Updated Column: 210679671
Updated Column: 210676607
Updated Column: 210678509
Updated Column: 210679361
Updated Column: 210679538
Updated Column: 210677182
Updated Column: 210680004
Updated Column: 210679177
Updated Column: 210678115
Updated Column: 210677691
Updated Column: 210677454
Updated Column: 210677675
Updated Column: 210677703
Updated Column: 210678385
Updated Column: 210677088
Updated Column: 210680821
Updated Column: 210673106
Updated Column: 210673088
Updated Column: 210673101
Updated Column: 210673096
Updated Column: 210673099
Updated Column: 210673104
Updated Column: 210673107
Updated Column: 210673089
Updated Column: 210673103
Updated Column: 210673105
Updated Column: 210677702
Updated Column: 210680320
Updated Column: 210680323
Updated Column: 210680335
Updated Column: 210680336
Updated Column: 210266277
Updated Column: 210680516
Updated Column: 210680513
Updated Column: 210679720
Updated Column: 210680338
Updated Column: 210677448
Updated Column: 210680337
Updated Column: 210680340
Updated Column: 210680322
Updated Column: 210266274
Updated Column: 210680707
Updated Column: 210679539
Updated Column: 210677912
Updated Column: 210679540
Updated Column: 210678116
Updated Column: 210677455
Updated Column: 210674861
Updated Column: 210679724
Updated Column: 210677452
Updated Column: 210675948
Updated Column: 210675852
Updated Column: 210675846
Updated Column: 210675853
Updated Column: 210675856
Updated Column: 210675857
Updated Column: 210675851
Updated Column: 210675947
Updated Column: 210675850
Updated Column: 210675949
Updated Column: 210675858
Updated Column: 210675845
Updated Column: 210675860
Updated Column: 210675855
Updated Column: 210675854
Updated Column: 210677458
Updated Column: 210268493
Updated Column: 210268490
Updated Column: 210268495
Updated Column: 210268496
Updated Column: 210268494
Updated Column: 210268497
Updated Column: 210678158
Updated Column: 210679756
Updated Column: 210679754
Updated Column: 210679753
Updated Column: 210679757
Updated Column: 210679749
Updated Column: 210680296
Updated Column: 210680318
Updated Column: 210680300
Updated Column: 210680319
Updated Column: 210680317
Updated Column: 210680294
Updated Column: 210680312
Updated Column: 210680292
Updated Column: 210680316
Updated Column: 210680315
Updated Column: 210680314
Updated Column: 210680303
Updated Column: 210680307
Updated Column: 210680306
Updated Column: 210680308
Updated Column: 210273840

In [33]:
import json

df['location'] = 'CA'
df['date'] = '072125'
df_j = df.to_json(orient='records', lines=True)

print(df_j)
# i=1
# for index, row in df.iterrows():
#     print(type(row))
#     a = row.to_json(orient='records', lines=True)
#     print(a)
#     print(f"Index: {index}, Row: {row}")
#     i += 1
#     if i > 3:
#         break

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [20]:
import os
result = os.popen("curl -X POST \"https://api.airtable.com/v0/entbiilze8Kao2jYh/edtv7pdm8oBXZHeDw/getRecords\" -H \"Authorization: Bearer patRgTOFAFiFMy6Yw.1fb5dc5717d88354eb7f4f5c6dd76a7907d5a656fd925d80b0201852117f82a3\" -H \"Content-Type: application/json\" --data '{ \"fields\": [] }'").read()
import pandas as pd

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  390k  100  390k  100    16   234k      9  0:00:01  0:00:01 --:--:--  233k

In [21]:
#print(result)
result = pd.read_json(result)

/tmp/ipykernel_1053561/2675009279.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  result = pd.read_json(result)

In [22]:
print(result)

                                         records  nextCursor
0     {'primaryKey': '1307301036', 'fields': {}}  h9hgujwweo
1     {'primaryKey': '1317106049', 'fields': {}}  h9hgujwweo
2     {'primaryKey': '2304208036', 'fields': {}}  h9hgujwweo
3     {'primaryKey': '1308102017', 'fields': {}}  h9hgujwweo
4     {'primaryKey': '2319403007', 'fields': {}}  h9hgujwweo
...                                          ...         ...
9995  {'primaryKey': '3429030046', 'fields': {}}  h9hgujwweo
9996  {'primaryKey': '3429030042', 'fields': {}}  h9hgujwweo
9997  {'primaryKey': '3429030039', 'fields': {}}  h9hgujwweo
9998  {'primaryKey': '3429030036', 'fields': {}}  h9hgujwweo
9999  {'primaryKey': '3429030065', 'fields': {}}  h9hgujwweo

[10000 rows x 2 columns]